// <auto-generated />
using System;
using LearnieService.LearnieDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnieService.Migrations
{
    [DbContext(typeof(LearnieDatabaseContext))]
    [Migration("20241105212911_Inil")]
    partial class Inil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnieService.Models.Answer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerID"));

                    b.Property<int>("AnswerContent")
                        .HasColumnType("int");

                    b.Property<bool>("IsRightAnswer")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("AnswerID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerID = 1,
                            AnswerContent = 1,
                            IsRightAnswer = false,
                            QuestionID = 2
                        },
                        new
                        {
                            AnswerID = 2,
                            AnswerContent = 2,
                            IsRightAnswer = true,
                            QuestionID = 3
                        },
                        new
                        {
                            AnswerID = 3,
                            AnswerContent = 3,
                            IsRightAnswer = false,
                            QuestionID = 4
                        },
                        new
                        {
                            AnswerID = 4,
                            AnswerContent = 4,
                            IsRightAnswer = true,
                            QuestionID = 5
                        },
                        new
                        {
                            AnswerID = 5,
                            AnswerContent = 5,
                            IsRightAnswer = false,
                            QuestionID = 6
                        },
                        new
                        {
                            AnswerID = 6,
                            AnswerContent = 6,
                            IsRightAnswer = true,
                            QuestionID = 7
                        },
                        new
                        {
                            AnswerID = 7,
                            AnswerContent = 7,
                            IsRightAnswer = false,
                            QuestionID = 8
                        },
                        new
                        {
                            AnswerID = 8,
                            AnswerContent = 8,
                            IsRightAnswer = true,
                            QuestionID = 9
                        },
                        new
                        {
                            AnswerID = 9,
                            AnswerContent = 9,
                            IsRightAnswer = false,
                            QuestionID = 10
                        },
                        new
                        {
                            AnswerID = 10,
                            AnswerContent = 10,
                            IsRightAnswer = true,
                            QuestionID = 11
                        },
                        new
                        {
                            AnswerID = 11,
                            AnswerContent = 11,
                            IsRightAnswer = false,
                            QuestionID = 12
                        },
                        new
                        {
                            AnswerID = 12,
                            AnswerContent = 12,
                            IsRightAnswer = true,
                            QuestionID = 13
                        },
                        new
                        {
                            AnswerID = 13,
                            AnswerContent = 13,
                            IsRightAnswer = false,
                            QuestionID = 14
                        },
                        new
                        {
                            AnswerID = 14,
                            AnswerContent = 14,
                            IsRightAnswer = true,
                            QuestionID = 15
                        },
                        new
                        {
                            AnswerID = 15,
                            AnswerContent = 15,
                            IsRightAnswer = false,
                            QuestionID = 16
                        },
                        new
                        {
                            AnswerID = 16,
                            AnswerContent = 16,
                            IsRightAnswer = true,
                            QuestionID = 17
                        },
                        new
                        {
                            AnswerID = 17,
                            AnswerContent = 17,
                            IsRightAnswer = false,
                            QuestionID = 18
                        },
                        new
                        {
                            AnswerID = 18,
                            AnswerContent = 18,
                            IsRightAnswer = true,
                            QuestionID = 19
                        },
                        new
                        {
                            AnswerID = 19,
                            AnswerContent = 19,
                            IsRightAnswer = false,
                            QuestionID = 20
                        },
                        new
                        {
                            AnswerID = 20,
                            AnswerContent = 20,
                            IsRightAnswer = true,
                            QuestionID = 21
                        },
                        new
                        {
                            AnswerID = 21,
                            AnswerContent = 21,
                            IsRightAnswer = false,
                            QuestionID = 22
                        },
                        new
                        {
                            AnswerID = 22,
                            AnswerContent = 22,
                            IsRightAnswer = true,
                            QuestionID = 23
                        },
                        new
                        {
                            AnswerID = 23,
                            AnswerContent = 23,
                            IsRightAnswer = false,
                            QuestionID = 24
                        },
                        new
                        {
                            AnswerID = 24,
                            AnswerContent = 24,
                            IsRightAnswer = true,
                            QuestionID = 25
                        },
                        new
                        {
                            AnswerID = 25,
                            AnswerContent = 25,
                            IsRightAnswer = false,
                            QuestionID = 26
                        },
                        new
                        {
                            AnswerID = 26,
                            AnswerContent = 26,
                            IsRightAnswer = true,
                            QuestionID = 27
                        },
                        new
                        {
                            AnswerID = 27,
                            AnswerContent = 27,
                            IsRightAnswer = false,
                            QuestionID = 28
                        },
                        new
                        {
                            AnswerID = 28,
                            AnswerContent = 28,
                            IsRightAnswer = true,
                            QuestionID = 29
                        },
                        new
                        {
                            AnswerID = 29,
                            AnswerContent = 29,
                            IsRightAnswer = false,
                            QuestionID = 30
                        },
                        new
                        {
                            AnswerID = 30,
                            AnswerContent = 30,
                            IsRightAnswer = true,
                            QuestionID = 31
                        },
                        new
                        {
                            AnswerID = 31,
                            AnswerContent = 31,
                            IsRightAnswer = false,
                            QuestionID = 32
                        },
                        new
                        {
                            AnswerID = 32,
                            AnswerContent = 32,
                            IsRightAnswer = true,
                            QuestionID = 33
                        },
                        new
                        {
                            AnswerID = 33,
                            AnswerContent = 33,
                            IsRightAnswer = false,
                            QuestionID = 34
                        },
                        new
                        {
                            AnswerID = 34,
                            AnswerContent = 34,
                            IsRightAnswer = true,
                            QuestionID = 35
                        },
                        new
                        {
                            AnswerID = 35,
                            AnswerContent = 35,
                            IsRightAnswer = false,
                            QuestionID = 36
                        },
                        new
                        {
                            AnswerID = 36,
                            AnswerContent = 36,
                            IsRightAnswer = true,
                            QuestionID = 37
                        },
                        new
                        {
                            AnswerID = 37,
                            AnswerContent = 37,
                            IsRightAnswer = false,
                            QuestionID = 38
                        },
                        new
                        {
                            AnswerID = 38,
                            AnswerContent = 38,
                            IsRightAnswer = true,
                            QuestionID = 39
                        },
                        new
                        {
                            AnswerID = 39,
                            AnswerContent = 39,
                            IsRightAnswer = false,
                            QuestionID = 40
                        },
                        new
                        {
                            AnswerID = 40,
                            AnswerContent = 40,
                            IsRightAnswer = true,
                            QuestionID = 41
                        },
                        new
                        {
                            AnswerID = 41,
                            AnswerContent = 41,
                            IsRightAnswer = false,
                            QuestionID = 42
                        },
                        new
                        {
                            AnswerID = 42,
                            AnswerContent = 42,
                            IsRightAnswer = true,
                            QuestionID = 43
                        },
                        new
                        {
                            AnswerID = 43,
                            AnswerContent = 43,
                            IsRightAnswer = false,
                            QuestionID = 44
                        },
                        new
                        {
                            AnswerID = 44,
                            AnswerContent = 44,
                            IsRightAnswer = true,
                            QuestionID = 45
                        },
                        new
                        {
                            AnswerID = 45,
                            AnswerContent = 45,
                            IsRightAnswer = false,
                            QuestionID = 46
                        },
                        new
                        {
                            AnswerID = 46,
                            AnswerContent = 46,
                            IsRightAnswer = true,
                            QuestionID = 47
                        },
                        new
                        {
                            AnswerID = 47,
                            AnswerContent = 47,
                            IsRightAnswer = false,
                            QuestionID = 48
                        },
                        new
                        {
                            AnswerID = 48,
                            AnswerContent = 48,
                            IsRightAnswer = true,
                            QuestionID = 49
                        },
                        new
                        {
                            AnswerID = 49,
                            AnswerContent = 49,
                            IsRightAnswer = false,
                            QuestionID = 50
                        },
                        new
                        {
                            AnswerID = 50,
                            AnswerContent = 50,
                            IsRightAnswer = true,
                            QuestionID = 1
                        });
                });

            modelBuilder.Entity("LearnieService.Models.Note", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteID"));

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionSetID")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NoteID");

                    b.HasIndex("QuestionSetID");

                    b.HasIndex("UserID");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            NoteID = 1,
                            NoteContent = "This is note 1",
                            QuestionSetID = 2,
                            UserEmail = "user2@example.com"
                        },
                        new
                        {
                            NoteID = 2,
                            NoteContent = "This is note 2",
                            QuestionSetID = 3,
                            UserEmail = "user3@example.com"
                        },
                        new
                        {
                            NoteID = 3,
                            NoteContent = "This is note 3",
                            QuestionSetID = 4,
                            UserEmail = "user4@example.com"
                        },
                        new
                        {
                            NoteID = 4,
                            NoteContent = "This is note 4",
                            QuestionSetID = 5,
                            UserEmail = "user5@example.com"
                        },
                        new
                        {
                            NoteID = 5,
                            NoteContent = "This is note 5",
                            QuestionSetID = 6,
                            UserEmail = "user6@example.com"
                        },
                        new
                        {
                            NoteID = 6,
                            NoteContent = "This is note 6",
                            QuestionSetID = 7,
                            UserEmail = "user7@example.com"
                        },
                        new
                        {
                            NoteID = 7,
                            NoteContent = "This is note 7",
                            QuestionSetID = 8,
                            UserEmail = "user8@example.com"
                        },
                        new
                        {
                            NoteID = 8,
                            NoteContent = "This is note 8",
                            QuestionSetID = 9,
                            UserEmail = "user9@example.com"
                        },
                        new
                        {
                            NoteID = 9,
                            NoteContent = "This is note 9",
                            QuestionSetID = 10,
                            UserEmail = "user10@example.com"
                        },
                        new
                        {
                            NoteID = 10,
                            NoteContent = "This is note 10",
                            QuestionSetID = 11,
                            UserEmail = "user1@example.com"
                        },
                        new
                        {
                            NoteID = 11,
                            NoteContent = "This is note 11",
                            QuestionSetID = 12,
                            UserEmail = "user2@example.com"
                        },
                        new
                        {
                            NoteID = 12,
                            NoteContent = "This is note 12",
                            QuestionSetID = 13,
                            UserEmail = "user3@example.com"
                        },
                        new
                        {
                            NoteID = 13,
                            NoteContent = "This is note 13",
                            QuestionSetID = 14,
                            UserEmail = "user4@example.com"
                        },
                        new
                        {
                            NoteID = 14,
                            NoteContent = "This is note 14",
                            QuestionSetID = 15,
                            UserEmail = "user5@example.com"
                        },
                        new
                        {
                            NoteID = 15,
                            NoteContent = "This is note 15",
                            QuestionSetID = 16,
                            UserEmail = "user6@example.com"
                        },
                        new
                        {
                            NoteID = 16,
                            NoteContent = "This is note 16",
                            QuestionSetID = 17,
                            UserEmail = "user7@example.com"
                        },
                        new
                        {
                            NoteID = 17,
                            NoteContent = "This is note 17",
                            QuestionSetID = 18,
                            UserEmail = "user8@example.com"
                        },
                        new
                        {
                            NoteID = 18,
                            NoteContent = "This is note 18",
                            QuestionSetID = 19,
                            UserEmail = "user9@example.com"
                        },
                        new
                        {
                            NoteID = 19,
                            NoteContent = "This is note 19",
                            QuestionSetID = 20,
                            UserEmail = "user10@example.com"
                        },
                        new
                        {
                            NoteID = 20,
                            NoteContent = "This is note 20",
                            QuestionSetID = 21,
                            UserEmail = "user1@example.com"
                        },
                        new
                        {
                            NoteID = 21,
                            NoteContent = "This is note 21",
                            QuestionSetID = 22,
                            UserEmail = "user2@example.com"
                        },
                        new
                        {
                            NoteID = 22,
                            NoteContent = "This is note 22",
                            QuestionSetID = 23,
                            UserEmail = "user3@example.com"
                        },
                        new
                        {
                            NoteID = 23,
                            NoteContent = "This is note 23",
                            QuestionSetID = 24,
                            UserEmail = "user4@example.com"
                        },
                        new
                        {
                            NoteID = 24,
                            NoteContent = "This is note 24",
                            QuestionSetID = 25,
                            UserEmail = "user5@example.com"
                        },
                        new
                        {
                            NoteID = 25,
                            NoteContent = "This is note 25",
                            QuestionSetID = 26,
                            UserEmail = "user6@example.com"
                        },
                        new
                        {
                            NoteID = 26,
                            NoteContent = "This is note 26",
                            QuestionSetID = 27,
                            UserEmail = "user7@example.com"
                        },
                        new
                        {
                            NoteID = 27,
                            NoteContent = "This is note 27",
                            QuestionSetID = 28,
                            UserEmail = "user8@example.com"
                        },
                        new
                        {
                            NoteID = 28,
                            NoteContent = "This is note 28",
                            QuestionSetID = 29,
                            UserEmail = "user9@example.com"
                        },
                        new
                        {
                            NoteID = 29,
                            NoteContent = "This is note 29",
                            QuestionSetID = 30,
                            UserEmail = "user10@example.com"
                        },
                        new
                        {
                            NoteID = 30,
                            NoteContent = "This is note 30",
                            QuestionSetID = 31,
                            UserEmail = "user1@example.com"
                        },
                        new
                        {
                            NoteID = 31,
                            NoteContent = "This is note 31",
                            QuestionSetID = 32,
                            UserEmail = "user2@example.com"
                        },
                        new
                        {
                            NoteID = 32,
                            NoteContent = "This is note 32",
                            QuestionSetID = 33,
                            UserEmail = "user3@example.com"
                        },
                        new
                        {
                            NoteID = 33,
                            NoteContent = "This is note 33",
                            QuestionSetID = 34,
                            UserEmail = "user4@example.com"
                        },
                        new
                        {
                            NoteID = 34,
                            NoteContent = "This is note 34",
                            QuestionSetID = 35,
                            UserEmail = "user5@example.com"
                        },
                        new
                        {
                            NoteID = 35,
                            NoteContent = "This is note 35",
                            QuestionSetID = 36,
                            UserEmail = "user6@example.com"
                        },
                        new
                        {
                            NoteID = 36,
                            NoteContent = "This is note 36",
                            QuestionSetID = 37,
                            UserEmail = "user7@example.com"
                        },
                        new
                        {
                            NoteID = 37,
                            NoteContent = "This is note 37",
                            QuestionSetID = 38,
                            UserEmail = "user8@example.com"
                        },
                        new
                        {
                            NoteID = 38,
                            NoteContent = "This is note 38",
                            QuestionSetID = 39,
                            UserEmail = "user9@example.com"
                        },
                        new
                        {
                            NoteID = 39,
                            NoteContent = "This is note 39",
                            QuestionSetID = 40,
                            UserEmail = "user10@example.com"
                        },
                        new
                        {
                            NoteID = 40,
                            NoteContent = "This is note 40",
                            QuestionSetID = 41,
                            UserEmail = "user1@example.com"
                        },
                        new
                        {
                            NoteID = 41,
                            NoteContent = "This is note 41",
                            QuestionSetID = 42,
                            UserEmail = "user2@example.com"
                        },
                        new
                        {
                            NoteID = 42,
                            NoteContent = "This is note 42",
                            QuestionSetID = 43,
                            UserEmail = "user3@example.com"
                        },
                        new
                        {
                            NoteID = 43,
                            NoteContent = "This is note 43",
                            QuestionSetID = 44,
                            UserEmail = "user4@example.com"
                        },
                        new
                        {
                            NoteID = 44,
                            NoteContent = "This is note 44",
                            QuestionSetID = 45,
                            UserEmail = "user5@example.com"
                        },
                        new
                        {
                            NoteID = 45,
                            NoteContent = "This is note 45",
                            QuestionSetID = 46,
                            UserEmail = "user6@example.com"
                        },
                        new
                        {
                            NoteID = 46,
                            NoteContent = "This is note 46",
                            QuestionSetID = 47,
                            UserEmail = "user7@example.com"
                        },
                        new
                        {
                            NoteID = 47,
                            NoteContent = "This is note 47",
                            QuestionSetID = 48,
                            UserEmail = "user8@example.com"
                        },
                        new
                        {
                            NoteID = 48,
                            NoteContent = "This is note 48",
                            QuestionSetID = 49,
                            UserEmail = "user9@example.com"
                        },
                        new
                        {
                            NoteID = 49,
                            NoteContent = "This is note 49",
                            QuestionSetID = 50,
                            UserEmail = "user10@example.com"
                        },
                        new
                        {
                            NoteID = 50,
                            NoteContent = "This is note 50",
                            QuestionSetID = 1,
                            UserEmail = "user1@example.com"
                        });
                });

            modelBuilder.Entity("LearnieService.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("OrderPrice")
                        .HasColumnType("float");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LearnieService.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionSetID")
                        .HasColumnType("int");

                    b.HasKey("QuestionID");

                    b.HasIndex("QuestionSetID");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            QuestionContent = "What is question 1?",
                            QuestionDescription = "Description for question 1",
                            QuestionSetID = 2
                        },
                        new
                        {
                            QuestionID = 2,
                            QuestionContent = "What is question 2?",
                            QuestionDescription = "Description for question 2",
                            QuestionSetID = 3
                        },
                        new
                        {
                            QuestionID = 3,
                            QuestionContent = "What is question 3?",
                            QuestionDescription = "Description for question 3",
                            QuestionSetID = 4
                        },
                        new
                        {
                            QuestionID = 4,
                            QuestionContent = "What is question 4?",
                            QuestionDescription = "Description for question 4",
                            QuestionSetID = 5
                        },
                        new
                        {
                            QuestionID = 5,
                            QuestionContent = "What is question 5?",
                            QuestionDescription = "Description for question 5",
                            QuestionSetID = 6
                        },
                        new
                        {
                            QuestionID = 6,
                            QuestionContent = "What is question 6?",
                            QuestionDescription = "Description for question 6",
                            QuestionSetID = 7
                        },
                        new
                        {
                            QuestionID = 7,
                            QuestionContent = "What is question 7?",
                            QuestionDescription = "Description for question 7",
                            QuestionSetID = 8
                        },
                        new
                        {
                            QuestionID = 8,
                            QuestionContent = "What is question 8?",
                            QuestionDescription = "Description for question 8",
                            QuestionSetID = 9
                        },
                        new
                        {
                            QuestionID = 9,
                            QuestionContent = "What is question 9?",
                            QuestionDescription = "Description for question 9",
                            QuestionSetID = 10
                        },
                        new
                        {
                            QuestionID = 10,
                            QuestionContent = "What is question 10?",
                            QuestionDescription = "Description for question 10",
                            QuestionSetID = 11
                        },
                        new
                        {
                            QuestionID = 11,
                            QuestionContent = "What is question 11?",
                            QuestionDescription = "Description for question 11",
                            QuestionSetID = 12
                        },
                        new
                        {
                            QuestionID = 12,
                            QuestionContent = "What is question 12?",
                            QuestionDescription = "Description for question 12",
                            QuestionSetID = 13
                        },
                        new
                        {
                            QuestionID = 13,
                            QuestionContent = "What is question 13?",
                            QuestionDescription = "Description for question 13",
                            QuestionSetID = 14
                        },
                        new
                        {
                            QuestionID = 14,
                            QuestionContent = "What is question 14?",
                            QuestionDescription = "Description for question 14",
                            QuestionSetID = 15
                        },
                        new
                        {
                            QuestionID = 15,
                            QuestionContent = "What is question 15?",
                            QuestionDescription = "Description for question 15",
                            QuestionSetID = 16
                        },
                        new
                        {
                            QuestionID = 16,
                            QuestionContent = "What is question 16?",
                            QuestionDescription = "Description for question 16",
                            QuestionSetID = 17
                        },
                        new
                        {
                            QuestionID = 17,
                            QuestionContent = "What is question 17?",
                            QuestionDescription = "Description for question 17",
                            QuestionSetID = 18
                        },
                        new
                        {
                            QuestionID = 18,
                            QuestionContent = "What is question 18?",
                            QuestionDescription = "Description for question 18",
                            QuestionSetID = 19
                        },
                        new
                        {
                            QuestionID = 19,
                            QuestionContent = "What is question 19?",
                            QuestionDescription = "Description for question 19",
                            QuestionSetID = 20
                        },
                        new
                        {
                            QuestionID = 20,
                            QuestionContent = "What is question 20?",
                            QuestionDescription = "Description for question 20",
                            QuestionSetID = 21
                        },
                        new
                        {
                            QuestionID = 21,
                            QuestionContent = "What is question 21?",
                            QuestionDescription = "Description for question 21",
                            QuestionSetID = 22
                        },
                        new
                        {
                            QuestionID = 22,
                            QuestionContent = "What is question 22?",
                            QuestionDescription = "Description for question 22",
                            QuestionSetID = 23
                        },
                        new
                        {
                            QuestionID = 23,
                            QuestionContent = "What is question 23?",
                            QuestionDescription = "Description for question 23",
                            QuestionSetID = 24
                        },
                        new
                        {
                            QuestionID = 24,
                            QuestionContent = "What is question 24?",
                            QuestionDescription = "Description for question 24",
                            QuestionSetID = 25
                        },
                        new
                        {
                            QuestionID = 25,
                            QuestionContent = "What is question 25?",
                            QuestionDescription = "Description for question 25",
                            QuestionSetID = 26
                        },
                        new
                        {
                            QuestionID = 26,
                            QuestionContent = "What is question 26?",
                            QuestionDescription = "Description for question 26",
                            QuestionSetID = 27
                        },
                        new
                        {
                            QuestionID = 27,
                            QuestionContent = "What is question 27?",
                            QuestionDescription = "Description for question 27",
                            QuestionSetID = 28
                        },
                        new
                        {
                            QuestionID = 28,
                            QuestionContent = "What is question 28?",
                            QuestionDescription = "Description for question 28",
                            QuestionSetID = 29
                        },
                        new
                        {
                            QuestionID = 29,
                            QuestionContent = "What is question 29?",
                            QuestionDescription = "Description for question 29",
                            QuestionSetID = 30
                        },
                        new
                        {
                            QuestionID = 30,
                            QuestionContent = "What is question 30?",
                            QuestionDescription = "Description for question 30",
                            QuestionSetID = 31
                        },
                        new
                        {
                            QuestionID = 31,
                            QuestionContent = "What is question 31?",
                            QuestionDescription = "Description for question 31",
                            QuestionSetID = 32
                        },
                        new
                        {
                            QuestionID = 32,
                            QuestionContent = "What is question 32?",
                            QuestionDescription = "Description for question 32",
                            QuestionSetID = 33
                        },
                        new
                        {
                            QuestionID = 33,
                            QuestionContent = "What is question 33?",
                            QuestionDescription = "Description for question 33",
                            QuestionSetID = 34
                        },
                        new
                        {
                            QuestionID = 34,
                            QuestionContent = "What is question 34?",
                            QuestionDescription = "Description for question 34",
                            QuestionSetID = 35
                        },
                        new
                        {
                            QuestionID = 35,
                            QuestionContent = "What is question 35?",
                            QuestionDescription = "Description for question 35",
                            QuestionSetID = 36
                        },
                        new
                        {
                            QuestionID = 36,
                            QuestionContent = "What is question 36?",
                            QuestionDescription = "Description for question 36",
                            QuestionSetID = 37
                        },
                        new
                        {
                            QuestionID = 37,
                            QuestionContent = "What is question 37?",
                            QuestionDescription = "Description for question 37",
                            QuestionSetID = 38
                        },
                        new
                        {
                            QuestionID = 38,
                            QuestionContent = "What is question 38?",
                            QuestionDescription = "Description for question 38",
                            QuestionSetID = 39
                        },
                        new
                        {
                            QuestionID = 39,
                            QuestionContent = "What is question 39?",
                            QuestionDescription = "Description for question 39",
                            QuestionSetID = 40
                        },
                        new
                        {
                            QuestionID = 40,
                            QuestionContent = "What is question 40?",
                            QuestionDescription = "Description for question 40",
                            QuestionSetID = 41
                        },
                        new
                        {
                            QuestionID = 41,
                            QuestionContent = "What is question 41?",
                            QuestionDescription = "Description for question 41",
                            QuestionSetID = 42
                        },
                        new
                        {
                            QuestionID = 42,
                            QuestionContent = "What is question 42?",
                            QuestionDescription = "Description for question 42",
                            QuestionSetID = 43
                        },
                        new
                        {
                            QuestionID = 43,
                            QuestionContent = "What is question 43?",
                            QuestionDescription = "Description for question 43",
                            QuestionSetID = 44
                        },
                        new
                        {
                            QuestionID = 44,
                            QuestionContent = "What is question 44?",
                            QuestionDescription = "Description for question 44",
                            QuestionSetID = 45
                        },
                        new
                        {
                            QuestionID = 45,
                            QuestionContent = "What is question 45?",
                            QuestionDescription = "Description for question 45",
                            QuestionSetID = 46
                        },
                        new
                        {
                            QuestionID = 46,
                            QuestionContent = "What is question 46?",
                            QuestionDescription = "Description for question 46",
                            QuestionSetID = 47
                        },
                        new
                        {
                            QuestionID = 47,
                            QuestionContent = "What is question 47?",
                            QuestionDescription = "Description for question 47",
                            QuestionSetID = 48
                        },
                        new
                        {
                            QuestionID = 48,
                            QuestionContent = "What is question 48?",
                            QuestionDescription = "Description for question 48",
                            QuestionSetID = 49
                        },
                        new
                        {
                            QuestionID = 49,
                            QuestionContent = "What is question 49?",
                            QuestionDescription = "Description for question 49",
                            QuestionSetID = 50
                        },
                        new
                        {
                            QuestionID = 50,
                            QuestionContent = "What is question 50?",
                            QuestionDescription = "Description for question 50",
                            QuestionSetID = 1
                        });
                });

            modelBuilder.Entity("LearnieService.Models.QuestionSet", b =>
                {
                    b.Property<int>("QuestionSetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionSetID"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("QuestSetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("QuestionSetID");

                    b.HasIndex("UserID");

                    b.ToTable("QuestionSets");

                    b.HasData(
                        new
                        {
                            QuestionSetID = 1,
                            CreatedAt = new DateOnly(2024, 11, 4),
                            QuestSetName = "Question Set 1",
                            UserID = 2
                        },
                        new
                        {
                            QuestionSetID = 2,
                            CreatedAt = new DateOnly(2024, 11, 3),
                            QuestSetName = "Question Set 2",
                            UserID = 3
                        },
                        new
                        {
                            QuestionSetID = 3,
                            CreatedAt = new DateOnly(2024, 11, 2),
                            QuestSetName = "Question Set 3",
                            UserID = 4
                        },
                        new
                        {
                            QuestionSetID = 4,
                            CreatedAt = new DateOnly(2024, 11, 1),
                            QuestSetName = "Question Set 4",
                            UserID = 5
                        },
                        new
                        {
                            QuestionSetID = 5,
                            CreatedAt = new DateOnly(2024, 10, 31),
                            QuestSetName = "Question Set 5",
                            UserID = 6
                        },
                        new
                        {
                            QuestionSetID = 6,
                            CreatedAt = new DateOnly(2024, 10, 30),
                            QuestSetName = "Question Set 6",
                            UserID = 7
                        },
                        new
                        {
                            QuestionSetID = 7,
                            CreatedAt = new DateOnly(2024, 10, 29),
                            QuestSetName = "Question Set 7",
                            UserID = 8
                        },
                        new
                        {
                            QuestionSetID = 8,
                            CreatedAt = new DateOnly(2024, 10, 28),
                            QuestSetName = "Question Set 8",
                            UserID = 9
                        },
                        new
                        {
                            QuestionSetID = 9,
                            CreatedAt = new DateOnly(2024, 10, 27),
                            QuestSetName = "Question Set 9",
                            UserID = 10
                        },
                        new
                        {
                            QuestionSetID = 10,
                            CreatedAt = new DateOnly(2024, 10, 26),
                            QuestSetName = "Question Set 10",
                            UserID = 1
                        },
                        new
                        {
                            QuestionSetID = 11,
                            CreatedAt = new DateOnly(2024, 10, 25),
                            QuestSetName = "Question Set 11",
                            UserID = 2
                        },
                        new
                        {
                            QuestionSetID = 12,
                            CreatedAt = new DateOnly(2024, 10, 24),
                            QuestSetName = "Question Set 12",
                            UserID = 3
                        },
                        new
                        {
                            QuestionSetID = 13,
                            CreatedAt = new DateOnly(2024, 10, 23),
                            QuestSetName = "Question Set 13",
                            UserID = 4
                        },
                        new
                        {
                            QuestionSetID = 14,
                            CreatedAt = new DateOnly(2024, 10, 22),
                            QuestSetName = "Question Set 14",
                            UserID = 5
                        },
                        new
                        {
                            QuestionSetID = 15,
                            CreatedAt = new DateOnly(2024, 10, 21),
                            QuestSetName = "Question Set 15",
                            UserID = 6
                        },
                        new
                        {
                            QuestionSetID = 16,
                            CreatedAt = new DateOnly(2024, 10, 20),
                            QuestSetName = "Question Set 16",
                            UserID = 7
                        },
                        new
                        {
                            QuestionSetID = 17,
                            CreatedAt = new DateOnly(2024, 10, 19),
                            QuestSetName = "Question Set 17",
                            UserID = 8
                        },
                        new
                        {
                            QuestionSetID = 18,
                            CreatedAt = new DateOnly(2024, 10, 18),
                            QuestSetName = "Question Set 18",
                            UserID = 9
                        },
                        new
                        {
                            QuestionSetID = 19,
                            CreatedAt = new DateOnly(2024, 10, 17),
                            QuestSetName = "Question Set 19",
                            UserID = 10
                        },
                        new
                        {
                            QuestionSetID = 20,
                            CreatedAt = new DateOnly(2024, 10, 16),
                            QuestSetName = "Question Set 20",
                            UserID = 1
                        },
                        new
                        {
                            QuestionSetID = 21,
                            CreatedAt = new DateOnly(2024, 10, 15),
                            QuestSetName = "Question Set 21",
                            UserID = 2
                        },
                        new
                        {
                            QuestionSetID = 22,
                            CreatedAt = new DateOnly(2024, 10, 14),
                            QuestSetName = "Question Set 22",
                            UserID = 3
                        },
                        new
                        {
                            QuestionSetID = 23,
                            CreatedAt = new DateOnly(2024, 10, 13),
                            QuestSetName = "Question Set 23",
                            UserID = 4
                        },
                        new
                        {
                            QuestionSetID = 24,
                            CreatedAt = new DateOnly(2024, 10, 12),
                            QuestSetName = "Question Set 24",
                            UserID = 5
                        },
                        new
                        {
                            QuestionSetID = 25,
                            CreatedAt = new DateOnly(2024, 10, 11),
                            QuestSetName = "Question Set 25",
                            UserID = 6
                        },
                        new
                        {
                            QuestionSetID = 26,
                            CreatedAt = new DateOnly(2024, 10, 10),
                            QuestSetName = "Question Set 26",
                            UserID = 7
                        },
                        new
                        {
                            QuestionSetID = 27,
                            CreatedAt = new DateOnly(2024, 10, 9),
                            QuestSetName = "Question Set 27",
                            UserID = 8
                        },
                        new
                        {
                            QuestionSetID = 28,
                            CreatedAt = new DateOnly(2024, 10, 8),
                            QuestSetName = "Question Set 28",
                            UserID = 9
                        },
                        new
                        {
                            QuestionSetID = 29,
                            CreatedAt = new DateOnly(2024, 10, 7),
                            QuestSetName = "Question Set 29",
                            UserID = 10
                        },
                        new
                        {
                            QuestionSetID = 30,
                            CreatedAt = new DateOnly(2024, 10, 6),
                            QuestSetName = "Question Set 30",
                            UserID = 1
                        },
                        new
                        {
                            QuestionSetID = 31,
                            CreatedAt = new DateOnly(2024, 10, 5),
                            QuestSetName = "Question Set 31",
                            UserID = 2
                        },
                        new
                        {
                            QuestionSetID = 32,
                            CreatedAt = new DateOnly(2024, 10, 4),
                            QuestSetName = "Question Set 32",
                            UserID = 3
                        },
                        new
                        {
                            QuestionSetID = 33,
                            CreatedAt = new DateOnly(2024, 10, 3),
                            QuestSetName = "Question Set 33",
                            UserID = 4
                        },
                        new
                        {
                            QuestionSetID = 34,
                            CreatedAt = new DateOnly(2024, 10, 2),
                            QuestSetName = "Question Set 34",
                            UserID = 5
                        },
                        new
                        {
                            QuestionSetID = 35,
                            CreatedAt = new DateOnly(2024, 10, 1),
                            QuestSetName = "Question Set 35",
                            UserID = 6
                        },
                        new
                        {
                            QuestionSetID = 36,
                            CreatedAt = new DateOnly(2024, 9, 30),
                            QuestSetName = "Question Set 36",
                            UserID = 7
                        },
                        new
                        {
                            QuestionSetID = 37,
                            CreatedAt = new DateOnly(2024, 9, 29),
                            QuestSetName = "Question Set 37",
                            UserID = 8
                        },
                        new
                        {
                            QuestionSetID = 38,
                            CreatedAt = new DateOnly(2024, 9, 28),
                            QuestSetName = "Question Set 38",
                            UserID = 9
                        },
                        new
                        {
                            QuestionSetID = 39,
                            CreatedAt = new DateOnly(2024, 9, 27),
                            QuestSetName = "Question Set 39",
                            UserID = 10
                        },
                        new
                        {
                            QuestionSetID = 40,
                            CreatedAt = new DateOnly(2024, 9, 26),
                            QuestSetName = "Question Set 40",
                            UserID = 1
                        },
                        new
                        {
                            QuestionSetID = 41,
                            CreatedAt = new DateOnly(2024, 9, 25),
                            QuestSetName = "Question Set 41",
                            UserID = 2
                        },
                        new
                        {
                            QuestionSetID = 42,
                            CreatedAt = new DateOnly(2024, 9, 24),
                            QuestSetName = "Question Set 42",
                            UserID = 3
                        },
                        new
                        {
                            QuestionSetID = 43,
                            CreatedAt = new DateOnly(2024, 9, 23),
                            QuestSetName = "Question Set 43",
                            UserID = 4
                        },
                        new
                        {
                            QuestionSetID = 44,
                            CreatedAt = new DateOnly(2024, 9, 22),
                            QuestSetName = "Question Set 44",
                            UserID = 5
                        },
                        new
                        {
                            QuestionSetID = 45,
                            CreatedAt = new DateOnly(2024, 9, 21),
                            QuestSetName = "Question Set 45",
                            UserID = 6
                        },
                        new
                        {
                            QuestionSetID = 46,
                            CreatedAt = new DateOnly(2024, 9, 20),
                            QuestSetName = "Question Set 46",
                            UserID = 7
                        },
                        new
                        {
                            QuestionSetID = 47,
                            CreatedAt = new DateOnly(2024, 9, 19),
                            QuestSetName = "Question Set 47",
                            UserID = 8
                        },
                        new
                        {
                            QuestionSetID = 48,
                            CreatedAt = new DateOnly(2024, 9, 18),
                            QuestSetName = "Question Set 48",
                            UserID = 9
                        },
                        new
                        {
                            QuestionSetID = 49,
                            CreatedAt = new DateOnly(2024, 9, 17),
                            QuestSetName = "Question Set 49",
                            UserID = 10
                        },
                        new
                        {
                            QuestionSetID = 50,
                            CreatedAt = new DateOnly(2024, 9, 16),
                            QuestSetName = "Question Set 50",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("LearnieService.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Subcription")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("SubcriptionExpiredAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SubcriptionStartAt")
                        .HasColumnType("date");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Birthday = "1990-01-01",
                            Fullname = "User One",
                            Subcription = true,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user1@example.com",
                            UserPassword = "password1"
                        },
                        new
                        {
                            UserID = 2,
                            Birthday = "1992-02-02",
                            Fullname = "User Two",
                            Subcription = false,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user2@example.com",
                            UserPassword = "password2"
                        },
                        new
                        {
                            UserID = 3,
                            Birthday = "1994-03-03",
                            Fullname = "User Three",
                            Subcription = true,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user3@example.com",
                            UserPassword = "password3"
                        },
                        new
                        {
                            UserID = 4,
                            Birthday = "1996-04-04",
                            Fullname = "User Four",
                            Subcription = false,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user4@example.com",
                            UserPassword = "password4"
                        },
                        new
                        {
                            UserID = 5,
                            Birthday = "1998-05-05",
                            Fullname = "User Five",
                            Subcription = true,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user5@example.com",
                            UserPassword = "password5"
                        },
                        new
                        {
                            UserID = 6,
                            Birthday = "2000-06-06",
                            Fullname = "User Six",
                            Subcription = false,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user6@example.com",
                            UserPassword = "password6"
                        },
                        new
                        {
                            UserID = 7,
                            Birthday = "2002-07-07",
                            Fullname = "User Seven",
                            Subcription = true,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user7@example.com",
                            UserPassword = "password7"
                        },
                        new
                        {
                            UserID = 8,
                            Birthday = "2004-08-08",
                            Fullname = "User Eight",
                            Subcription = false,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user8@example.com",
                            UserPassword = "password8"
                        },
                        new
                        {
                            UserID = 9,
                            Birthday = "2006-09-09",
                            Fullname = "User Nine",
                            Subcription = true,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user9@example.com",
                            UserPassword = "password9"
                        },
                        new
                        {
                            UserID = 10,
                            Birthday = "2008-10-10",
                            Fullname = "User Ten",
                            Subcription = false,
                            SubcriptionExpiredAt = new DateOnly(2024, 11, 5),
                            SubcriptionStartAt = new DateOnly(2024, 11, 5),
                            UserEmail = "user10@example.com",
                            UserPassword = "password10"
                        });
                });

            modelBuilder.Entity("LearnieService.Models.Answer", b =>
                {
                    b.HasOne("LearnieService.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("LearnieService.Models.Note", b =>
                {
                    b.HasOne("LearnieService.Models.QuestionSet", "QuestionSet")
                        .WithMany("Note")
                        .HasForeignKey("QuestionSetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnieService.Models.User", null)
                        .WithMany("Notes")
                        .HasForeignKey("UserID");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("LearnieService.Models.Order", b =>
                {
                    b.HasOne("LearnieService.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnieService.Models.Question", b =>
                {
                    b.HasOne("LearnieService.Models.QuestionSet", "QuestionSet")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionSetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("LearnieService.Models.QuestionSet", b =>
                {
                    b.HasOne("LearnieService.Models.User", "CreatedBy")
                        .WithMany("QuestionSets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LearnieService.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LearnieService.Models.QuestionSet", b =>
                {
                    b.Navigation("Note");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LearnieService.Models.User", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Orders");

                    b.Navigation("QuestionSets");
                });
#pragma warning restore 612, 618
        }
    }
}
